version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - type: bind
        source: ./html
        target: /var/www/html
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
  app:
    build:
     context: .
     dockerfile: Dockerfile
    image: sneaker
    env_file:
     - ${APP_ENV}.env
    volumes:
      - type: bind
        source: ./html
        target: /var/www/html
      - type: bind
        source: ./php.ini
        target: /usr/local/etc/php/php.ini
  db:
    image: mysql:5.7.29
    volumes:
      - type: bind
        source: ./initdb.d/${APP_ENV}
        target: /docker-entrypoint-initdb.d
    env_file:
     - ${APP_ENV}.env
